// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://livspace.io",
        "contact": {
            "name": "Ankit",
            "url": "https://livspace.io",
            "email": "ankit.a@livspace.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/check": {
            "get": {
                "description": "check token and policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "auth check",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "subject",
                        "name": "subject_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "resource",
                        "name": "object",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "access-type",
                        "name": "relation",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    }
                }
            }
        },
        "/auth/expand": {
            "get": {
                "description": "expand relation tuple",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "expand relation tuple",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "subject",
                        "name": "subject_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "resource",
                        "name": "object",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "access-type",
                        "name": "relation",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    }
                }
            }
        },
        "/auth/relation_tuples": {
            "get": {
                "description": "query relation tuple",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "query relation tuple",
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "subject",
                        "name": "subject_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "resource",
                        "name": "object",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "access-type",
                        "name": "relation",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "create relation tuple",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "create relation tuple",
                "parameters": [
                    {
                        "description": "Relation Data",
                        "name": "relation_tuple",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RelationTuple"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete relation tuple",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "delete relation tuple",
                "parameters": [
                    {
                        "description": "Relation Data",
                        "name": "relation_tuple",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RelationTuple"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.KetoResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "check health",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.KetoResponse": {
            "type": "object",
            "properties": {
                "allowed": {
                    "type": "boolean",
                    "format": "bool",
                    "example": true
                },
                "code": {
                    "type": "integer",
                    "format": "int64",
                    "example": 403
                },
                "message": {
                    "type": "string",
                    "example": "Access Forbidden"
                },
                "reason": {
                    "type": "string",
                    "example": "Subject does not have access"
                },
                "request": {
                    "type": "string",
                    "example": "xyz"
                },
                "status": {
                    "type": "string",
                    "example": "403"
                }
            }
        },
        "model.RelationTuple": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string",
                    "example": "canvas"
                },
                "object": {
                    "type": "string",
                    "example": "project-123"
                },
                "relation": {
                    "type": "string",
                    "example": "read"
                },
                "subject_id": {
                    "type": "string",
                    "example": "user-123"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Ozone API",
	Description:      "An auth layer for APIs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
