basePath: /api/v1
definitions:
  model.KetoResponse:
    properties:
      allowed:
        example: true
        format: bool
        type: boolean
      code:
        example: 403
        format: int64
        type: integer
      message:
        example: Access Forbidden
        type: string
      reason:
        example: Subject does not have access
        type: string
      request:
        example: xyz
        type: string
      status:
        example: "403"
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: ankit.a@livspace.com
    name: Ankit
    url: https://livspace.io
  description: An auth layer for APIs
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://livspace.io
  title: Ozone API
  version: "1.0"
paths:
  /auth/check:
    get:
      consumes:
      - application/json
      description: check token and policy
      parameters:
      - description: namespace
        in: query
        name: namespace
        required: true
        type: string
      - description: resource
        in: query
        name: object
        required: true
        type: string
      - description: access-type
        in: query
        name: relation
        required: true
        type: string
      - description: Bearer <Bouncer_access_token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.KetoResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.KetoResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.KetoResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.KetoResponse'
      summary: auth check
      tags:
      - auth
  /auth/expand:
    get:
      consumes:
      - application/json
      description: expand relation tuple
      parameters:
      - description: namespace
        in: query
        name: namespace
        required: true
        type: string
      - description: max-depth to expand tuple
        in: query
        name: max-depth
        required: true
        type: integer
      - description: resource
        in: query
        name: object
        required: true
        type: string
      - description: access-type
        in: query
        name: relation
        required: true
        type: string
      - description: Bearer <Bouncer_access_token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.KetoResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.KetoResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.KetoResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.KetoResponse'
      summary: expand relation tuple
      tags:
      - auth
  /auth/relation_tuples:
    get:
      consumes:
      - application/json
      description: query relation tuple
      parameters:
      - description: namespace
        in: query
        name: namespace
        required: true
        type: string
      - description: subject
        in: query
        name: subject_id
        required: true
        type: string
      - description: resource
        in: query
        name: object
        required: true
        type: string
      - description: access-type
        in: query
        name: relation
        required: true
        type: string
      - description: subject_set namespace
        in: query
        name: subject_set.namespace
        required: true
        type: string
      - description: subject_set object
        in: query
        name: subject_set.object
        required: true
        type: string
      - description: subject_set relation
        in: query
        name: subject_set.relation
        required: true
        type: string
      - description: Bearer <Bouncer_access_token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.KetoResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.KetoResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/model.KetoResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.KetoResponse'
      summary: query relation tuple
      tags:
      - auth
  /health:
    get:
      consumes:
      - application/json
      description: check health
      parameters:
      - description: Bearer <Bouncer_access_token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: health check
      tags:
      - health
schemes:
- http
swagger: "2.0"
